# Generated by Django 3.0.3 on 2020-02-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_auto_20200224_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='fact_close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='days',
            name='fact_open_time',
            field=models.TimeField(null=True),
        ),
    ]
