# Generated by Django 3.0.3 on 2020-02-24 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_auto_20200224_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='items',
            name='note',
            field=models.CharField(max_length=200),
        ),
    ]
