# Generated by Django 3.0.3 on 2020-02-24 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_auto_20200224_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='cleansing',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='days',
            name='date',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
        migrations.AlterField(
            model_name='days',
            name='fact_close_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='days',
            name='fact_open_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='days',
            name='setup',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
