# Generated by Django 3.0.3 on 2020-02-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_auto_20200228_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='worker',
            field=models.CharField(choices=[('satish kumar', 'SATISH KUMAR'), ('rona ji', 'RONA JI'), ('ishwar lal', 'ISHWAR LAL'), ('babu', 'BABU'), ('sanjay', 'SANJAY')], default='select', max_length=50),
        ),
    ]
