# Generated by Django 3.0.3 on 2020-03-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0013_auto_20200301_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='date',
            field=models.DateField(),
        ),
    ]
