# Generated by Django 3.0.3 on 2020-03-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0015_auto_20200301_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='iweight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='items',
            name='rweight',
            field=models.FloatField(default=0.0),
        ),
    ]
