# Generated by Django 3.0.3 on 2020-03-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0017_auto_20200303_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
