# Generated by Django 3.0.3 on 2020-03-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0021_auto_20200306_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='iweight',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AlterField(
            model_name='items',
            name='rweight',
            field=models.FloatField(default='0.0'),
        ),
    ]
