# Generated by Django 3.0.3 on 2020-03-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0023_auto_20200321_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='note',
        ),
        migrations.AddField(
            model_name='items',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
