# Generated by Django 3.0.3 on 2020-03-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0024_auto_20200321_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='factorylog_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cal.factorylog'),
        ),
    ]
