# Generated by Django 3.0.3 on 2020-03-23 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0025_notes_factorylog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='factorylog_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factorylog_id', to='cal.factorylog'),
        ),
    ]
