# Generated by Django 3.0.3 on 2020-03-25 03:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0026_auto_20200323_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('item_id', models.IntegerField(default='0', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('offset', models.FloatField(default='0.0')),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('updated_date', models.DateField(default=datetime.date.today)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='item_preparation_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rweight', models.FloatField(default='0.0')),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('grade', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('date', models.DateField(default=datetime.date.today)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cal.item')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup', models.TextField(blank=True, max_length=1000, null=True)),
                ('cleansing', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('worker_id', models.IntegerField(default='0', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='notes',
            name='factorylog_id',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='factorylog',
            name='id',
        ),
        migrations.AddField(
            model_name='factorylog',
            name='factorylog_id',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='factorylog',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='items',
        ),
        migrations.DeleteModel(
            name='notes',
        ),
        migrations.AddField(
            model_name='note',
            name='factorylog_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cal.factorylog'),
        ),
        migrations.AddField(
            model_name='item_preparation_detail',
            name='worker_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cal.worker'),
        ),
    ]
