# Generated by Django 3.0.3 on 2020-04-01 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0027_auto_20200325_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorylog',
            name='factorylog_id',
            field=models.PositiveIntegerField(default='0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.PositiveIntegerField(default='0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_id',
            field=models.PositiveIntegerField(default='0', primary_key=True, serialize=False),
        ),
    ]
