# Generated by Django 3.0.3 on 2020-04-23 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0028_auto_20200401_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='factorylog_id',
        ),
        migrations.AddField(
            model_name='factorylog',
            name='note_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cal.note'),
        ),
        migrations.AlterField(
            model_name='factorylog',
            name='factorylog_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item_preparation_detail',
            name='grade',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.PositiveIntegerField(default='0', primary_key=True, serialize=False),
        ),
    ]
