# Generated by Django 3.0.3 on 2020-04-23 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0029_auto_20200422_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='id',
            new_name='note_id',
        ),
    ]
