# Generated by Django 3.0.3 on 2020-04-23 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0030_auto_20200422_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factorylog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='note',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
