# Generated by Django 3.0.3 on 2020-04-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0031_auto_20200422_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
