# Generated by Django 3.0.3 on 2020-04-23 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0032_auto_20200422_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorylog',
            name='note_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cal.note'),
        ),
    ]
