# Generated by Django 3.0.3 on 2020-04-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0033_auto_20200422_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_preparation_detail',
            name='grade',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1),
        ),
    ]
